### PR TITLE
增加kcp websocks的设定

### PR DESCRIPTION
**Pull request by rico93**
写了 kcp和websocks的设定.

### CODE REVIEW

**Comment by ThunderingII** [comment]
Config.py 这个文件能不能使用config.ini等代替掉，我目前把这个文件的内容合并到了主文件里面了

**Comment by rico93** [comment]
可以的，我自己用的时候，直接调用了，解析出来包里的设定值。

**Comment by ThunderingII** [comment]
因为有文件冲突，我中午的时候再合并，我看看是不是把你的配置信息直接写道config.ini里面去，不然一个config.ini一个.py很奇怪

**Comment by rico93** [comment]
那个 可以直接这么写 

`
from v2ray.com.core.proxy.shadowsocks import config_pb2 as shadowsocks_server_config_pb2
import v2ray.com.core.transport.internet.config_pb2 as internet_config_pb2
from v2ray.com.core.transport.internet.websocket import config_pb2 as websocket_config_pb2
from v2ray.com.core.transport.internet.headers.wechat import config_pb2 as header_wechat_config_pb2
from v2ray.com.core.transport.internet.headers.srtp import config_pb2 as header_srtp_config_pb2
from v2ray.com.core.transport.internet.headers.utp import config_pb2 as header_utp_config_pb2
from v2ray.com.core.transport.internet.headers.wireguard import config_pb2 as header_wiregurad_config_pb2
from v2ray.com.core.transport.internet.kcp import config_pb2 as kcp_config_pb2
from v2ray.com.core.transport.internet.headers.tls import config_pb2 as header_tls_config_pb2
from v2ray.com.core.transport.internet.headers.noop import config_pb2 as header_noop_config_pb2
from v2ray.com.core.common.net.network_pb2 import TCP,UDP

KCP_HEADERS_CONFIG = {"wechat-video": header_wechat_config_pb2.VideoConfig(), "srtp": header_srtp_config_pb2.Config(),
                      'utp': header_utp_config_pb2.Config(),
                      'wireguard': header_wiregurad_config_pb2.WireguardConfig(),
                      'dtls': header_tls_config_pb2.PacketConfig(),
                      "noop": header_noop_config_pb2.Config()}

CIPHER_TYPE_MAP = {"aes-256-cfb": shadowsocks_server_config_pb2.AES_256_CFB,
                   "aes-128-cfb": shadowsocks_server_config_pb2.AES_128_CFB,
                   "aes-128-gcm": shadowsocks_server_config_pb2.AES_128_GCM,
                   "aes-256-gcm": shadowsocks_server_config_pb2.AES_256_GCM,
                   "chacha20": shadowsocks_server_config_pb2.CHACHA20,
                   "chacah-ietf": shadowsocks_server_config_pb2.CHACHA20_IETF,
                   'chacha20-ploy1305': shadowsocks_server_config_pb2.CHACHA20_POLY1305,
                   "chacha20-ietf-poly1305":shadowsocks_server_config_pb2.CHACHA20_POLY1305,}

`
以下这两个放进 config.ini 就好了
`
AUTO = 0
DISABLE = 1
ENABLE = 2
`

**Pull request merged**
